//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InRule.Authoring.AWS.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.0.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\dreynolds.INRULE\\Desktop\\AWS\\Blog\\rules.zip")]
        public string ZipFilePath {
            get {
                return ((string)(this["ZipFilePath"]));
            }
            set {
                this["ZipFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\dreynolds.INRULE\\Desktop\\AWS\\Blog\\rules.js")]
        public string RuleFilePath {
            get {
                return ((string)(this["RuleFilePath"]));
            }
            set {
                this["RuleFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\dreynolds.INRULE\\Desktop\\AWS\\Blog\\index.js")]
        public string IndexFilePath {
            get {
                return ((string)(this["IndexFilePath"]));
            }
            set {
                this["IndexFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\dreynolds.INRULE\\Desktop\\AWS\\Blog\\indexTemplate.js")]
        public string IndexFileTemplatePath {
            get {
                return ((string)(this["IndexFileTemplatePath"]));
            }
            set {
                this["IndexFileTemplatePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AwsAccessKeyId {
            get {
                return ((string)(this["AwsAccessKeyId"]));
            }
            set {
                this["AwsAccessKeyId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AwsSecretKey {
            get {
                return ((string)(this["AwsSecretKey"]));
            }
            set {
                this["AwsSecretKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string InRuleDistKey {
            get {
                return ((string)(this["InRuleDistKey"]));
            }
            set {
                this["InRuleDistKey"] = value;
            }
        }
    }
}
